baseurl: "/newsstream-audio-alignment" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://dpa-newslab.github.io" # the base hostname & protocol for your site
title: "newsstream Audio Alignment"
logo: "img/newsstream-logo-125x25.png"
# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

#gems:
#  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
